apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "inforiver.name" . }}-api
  namespace: {{ include "inforiver.name" . }}
  labels:
    role: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "inforiver.name" . }}-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ include "inforiver.name" . }}-api
    spec:
      containers:
      - env:        
        - name: ADMIN_PORTAL_URL
          value: {{ .Values.env.ADMIN_PORTAL_URL }}
        - name: APP_HOST
          value: {{ .Values.env.APP_HOST }}
        - name: APP_LOGO
          value: "https://turing-staging.inforiver.com/public/img/inforiver_logo.png"
        - name: APP_NAME
          value: Inforiver
        - name: APP_PORT
          value: "443"
        - name: AWS_REGION
          value: {{ .Values.env.AWS_REGION }} 
        - name: BLOB_CONTAINER_NAME
          value: {{ .Values.env.BLOB_CONTAINER_NAME}}        
        - name: BOOTSTRAP_ON_PREMISE
          value: "true"
        - name: BOOTSTRAP_ON_PREMISE_WORKSPACE_ADMIN
          value: {{ .Values.env.BOOTSTRAP_ON_PREMISE_WORKSPACE_ADMIN }}
        - name: BOOTSTRAP_ON_PREMISE_WORKSPACE_DOMAIN
          value: {{ .Values.env.BOOTSTRAP_ON_PREMISE_WORKSPACE_DOMAIN }}
        - name: BOOTSTRAP_ON_PREMISE_WORKSPACE_LICENSE
          value: {{ .Values.env.BOOTSTRAP_ON_PREMISE_WORKSPACE_LICENSE }}
        - name: BOOTSTRAP_ON_PREMISE_WORKSPACE_NAME
          value: {{ .Values.env.BOOTSTRAP_ON_PREMISE_WORKSPACE_NAME }}  
        - name: CLOUD_SERVICE_PROVIDER
          value: aws                    
        - name: COMMENTWORKER_QUEUE_NAME
          value: turing-comment-immediate
        - name: CRON_AKS_POD_TTL
          value: "16000"        
        - name: CRON_CONTAINER_IMAGE
          value: {{ .Values.image.repository }}/turing-worker:{{ .Values.image.tag | default .Chart.AppVersion }}
        - name: CRON_EMBED_FUNCTION_THRESHOLD
          value: '50000'
        - name: CRON_PAGE_LOAD_VALIDATE_WAIT_TIME
          value: '50000'  
        - name: DB_ENCRYPT
          value: "true"
        - name: DB_HOST
          value: {{ .Values.env.DB_HOST }}    
        - name: DB_NAME
          value: {{ .Values.env.DB_NAME }}
        - name: DB_PASS
          value: {{ .Values.env.DB_PASS }}
        - name: DB_PORT
          value: "1433"
        - name: DB_SCHEMA
          value: dbo
        - name: DB_TYPE
          value: mssql
        - name: DB_USER
          value: {{ .Values.env.DB_USER }}
        - name: DOCKER_ENABLE_CI
          value: "true"
        - name: DOCKER_REGISTRY_SERVER_PASSWORD
          value: {{ .Values.env.DOCKER_REGISTRY_SERVER_PASSWORD}}
        - name: DOCKER_REGISTRY_SERVER_URL
          value: "https://turing.azurecr.io"
        - name: DOCKER_REGISTRY_SERVER_USERNAME
          value: turing
        - name: DUCKDB_MOUNT_PATH
          value: /mnt/efs  
        - name: ETLWORKER_WAREHOUSE_PATH
          value: "warehouse"  
        - name: ENABLE_AUDIT
          value: "1"
        - name: FABRIC_WAREHOUSE_BLOB_INSERT_TENANTS
          value: "3"
        - name: FABRIC_WAREHOUSE_STORAGE_ACCOUNT_KEY
          value: {{ .Values.env.FABRIC_WAREHOUSE_STORAGE_ACCOUNT_KEY}}
        - name: FABRIC_WAREHOUSE_STORAGE_ACCOUNT_NAME
          value: {{ .Values.env.FABRIC_WAREHOUSE_STORAGE_ACCOUNT_NAME}}     
        - name: GET_JOB_USAGE_REPORT
          value: "0"
        - name: GOOGLE_APP_CLIENT_ID
          value: {{ .Values.env.GOOGLE_APP_CLIENT_ID}}
        - name: GOOGLE_APP_SECRET_ID
          value: {{ .Values.env.GOOGLE_APP_SECRET_ID}}  
        - name: IS_TEST
          value: "2"       
        - name: LINKEDIN_APP_CLIENT_ID
          value: {{ .Values.env.LINKEDIN_APP_CLIENT_ID}}
        - name: LINKEDIN_APP_SECRET_ID
          value: {{ .Values.env.LINKEDIN_APP_SECRET_ID}}
        - name: MODE
          value: AKS
        - name: O365_APP_CLIENT_ID
          value: {{ .Values.env.O365_APP_CLIENT_ID }}
        - name: O365_APP_SECRET_ID
          value: {{ .Values.env.O365_APP_SECRET_ID }}
        - name: O365_APP_TENANT_ID
          value: {{ .Values.env.O365_APP_TENANT_ID }}
        - name: ORCHESTRATOR_AKS_CPU_LIMIT
          value: 2000m
        - name: ORCHESTRATOR_AKS_CPU_REQUEST
          value: 1000m
        - name: ORCHESTRATOR_AKS_MEMORY_THRESHOLDS
          value: |
            {"0-100000":{"memoryLimit":"3096Mi","memoryRequest":"1024Mi"},"100001-200000":{"memoryLimit":"4096Mi","memoryRequest":"2048Mi"},"200001-400000":{"memoryLimit":"5096Mi","memoryRequest":"3096Mi"},"400001-2000000":{"memoryLimit":"6096Mi","memoryRequest":"4096Mi"}}
        - name: ORCHESTRATOR_AKS_POD_TTL
          value: "16000"
        - name: ORCHESTRATOR_APPSOURCE_TENANT_CRON_JOB_ENABLE
          value: "0"
        - name: ORCHESTRATOR_RETENTION_CONTROLS_ENABLED
          value: "1"
        - name: ORCHESTRATOR_DATAFLOW_AKS_MEMORY_LIMIT
          value: 4Gi
        - name: ORCHESTRATOR_PERSISTENT_VOLUME_CLAIM
          value: {{ include "inforiver.name" . }}-pvc
        - name: ORCHESTRATOR_PERSISTENT_VOLUME_NAME
          value: {{ include "inforiver.name" . }}-pv 
        - name: ORCHESTRATOR_DATAFLOW_WORKER_CONTAINER_IMAGE
          value: {{ .Values.image.repository }}/turing-datasource-integration-worker:{{ .Values.image.tag | default .Chart.AppVersion }} 
        - name: ORCHESTRATOR_VISUAL_WORKER_CONTAINER_IMAGE
          value: {{ .Values.image.repository }}/turing-visual-worker:{{ .Values.image.tag | default .Chart.AppVersion }}
        - name: ORCHESTRATOR_WRITEBACK_WORKER_CONTAINER_IMAGE
          value: {{ .Values.image.repository }}/turing-writeback-worker:{{ .Values.image.tag | default .Chart.AppVersion }}
        - name: PAGE_LOAD_WAIT_TIME
          value: "150000"
        - name: PORT
          value: "{{ .Values.ports.containerPort }}"
        - name: PREVIEW_ZIP_SIZE_LIMIT_IN_MB
          value: "1"
        - name: PROTOCOL
          value: https 
        - name: PRODUCT_BUILD
          value: common   
        - name: REDIS_HOST
          value: {{ .Values.env.REDIS_HOST }}        
        - name: REDIS_PASSWORD
          value: "{{ .Values.env.REDIS_PASSWORD }}"
        - name: REDIS_PORT
          value: "{{ .Values.env.REDIS_PORT }}"
        - name: REDIS_TLS_ENABLED
          value: "1"
        - name: SMTP_API_KEY
          value: {{ .Values.env.SMTP_API_KEY }}
        - name: SMTP_HOST
          value: {{ .Values.env.SMTP_HOST }}
        - name: SMTP_PORT
          value: "{{ .Values.env.SMTP_PORT }}"
        - name: SMTP_SERVICE
          value: "{{ .Values.env.SMTP_SERVICE }}"
        - name: SMTP_USERNAME
          value: {{ .Values.env.SMTP_USERNAME }}
        - name: SMTP_TLS_ENABLED
          value: "0" 
        - name: SSL_CERT
          value: "Y"             
        - name: SUPPORTED_VISUAL_GUID
          value: 2B7A5FD2992D434DAE0B149479307B7B
        - name: VALIDATE_REPORT_WAIT_TIME
          value: "9000"
        - name: WEBHOOK_KEY
          value: {{ .Values.env.WEBHOOK_KEY }}  
        - name: WORKER_QUEUE_NAME
          value: turing-email-notification
        - name: WRITEBACK_PAYLOAD_AKS_THRESHOLD
          value: "150000"                     
        image: {{ .Values.image.repository }}/turing-api:{{ .Values.image.tag | default .Chart.AppVersion }}
        imagePullPolicy: Always
        name: {{ include "inforiver.name" . }}-api
        ports:
        - containerPort: {{ .Values.ports.containerPort }}
        resources:
          limits:
            cpu: 3000m
            memory: 6Gi
          requests:
            cpu: 2500m
            memory: 2Gi
      imagePullSecrets:
      - name: {{ include "inforiver.name" . }}-docker-secret
      restartPolicy: Always
      terminationGracePeriodSeconds: 30