apiVersion: v1
kind: ServiceAccount
metadata:
  meta.helm.sh/release-name: inforiverdeployment
  meta.helm.sh/release-namespace: default
  labels:
    app.kubernetes.io/name: aws-efs-csi-driver
    app.kubernetes.io/managed-by: Helm
  name: efs-csi-controller-sa
  namespace: kube-system
  annotations:
    eks.amazonaws.com/role-arn: {{ .Values.role.ROLE_ARN}}