kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: {{ include "inforiver.name" . }}-pv
provisioner: efs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
mountOptions:
  - tls
parameters:
  provisioningMode: efs-ap
  fileSystemId: {{ .Values.pv.efs_id}}
  directoryPerms: "700"
  gidRangeStart: "1000"
  gidRangeEnd: "2000"
  basePath: "/data"

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "inforiver.name" . }}-pv
spec:
  capacity:
    storage: 32Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: {{ include "inforiver.name" . }}-pv
  csi:
    driver: efs.csi.aws.com
    volumeHandle: {{ .Values.pv.efs_id}}

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "inforiver.name" . }}-pvc
  namespace: {{ include "inforiver.name" . }}
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: {{ include "inforiver.name" . }}-pv
  resources:
    requests:
      storage: 5Gi